# Disable the blank line at the start of the prompt
add_newline = false
format = """$character$directory"""
right_format = """$all"""

[character]
success_symbol = '[➜](bold #ff5555) '
error_symbol = '[✗](bold #50fa7b) '

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[package]
disabled = true

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

