# Disable the blank line at the start of the prompt
add_newline = false
format = """$character$directory"""
right_format = """$all"""

[character]
success_symbol = '[➜](bold #98BB6C) '
error_symbol = '[✗](bold #E82424) '

[directory]
style = "bold #7E9CD8"

[git_branch]
style = "bold bright-black"

[git_status]
style = "bold #DCA561"

[package]
disabled = true
